working_directory = "/Users/timmoses/Documents/Tech/Projects/Version_controlled/Assignment/"
event_ids = ["Fri May 29", "Fri Jun 5", "Fri Jun 12", "Fri Jun 19", "Sat Jun 27", "Fri Jul 3", "Fri Jul 10", "Sat Jul 18", "Fri Jul 24", "Fri Jul 31", "Sat Aug 8", "Fri Aug 14", "Fri Aug 21", "Sat Aug 29", "Fri Sep 4", "Fri Sep 11", "Fri Sep 18", "Fri Sep 25"]
boat_header_row = ["key","owner key","display name","email address","mobile","female","min occupancy","max occupancy","assistance"]
sailor_header_row = ["key","display name","partner key","email address","member","skill","experience","request female","whitelist"]
debug_header_row = ["date","interim","final","explanation"]
default_boat = { "key" : "", "owner key" : "", "display name" : "", "email address" : "","mobile" : "", "female" : "False", "min occupancy" : "1", "max occupancy" : "1", "assistance" : "False" }
default_sailor = { "key" : "", "display name" : "", "partner key" : "", "email address" : "", "member" : "False", "skill" : "0", "experience" : "", "request female" : "False","whitelist" : ""}
rules = ["assist", "whitelist", "skill", "partner", "repeat"]
streak = 2 # Minimum compliant gap between repeats.
min_membership_number_length = 4 # Genuine membership numbers may be 6 to 9 digits in length.
max_membership_number_length = 9
global_epochs = 8 # Iterations to find 'global' minimum.
local_epochs = 6 # Iterations to find 'local' minimum.
assist_weight = 16
whitelist_weight = 8
skill_weight = 4
partner_weight = 2
repeat_weight = 1
cut_off = 6 # Days prior to the event during which crew positions may be guaranteed.